######################################################################
# Automatically generated by qmake (3.0) ?? 7? 23 21:36:29 2014
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += ../PluginLoader.hpp ../dubway-global.hpp
SOURCES += test.cpp
