######################################################################
# Automatically generated by qmake (3.0) ?? 7? 23 21:08:40 2014
######################################################################

TEMPLATE = lib
TARGET = plugin
INCLUDEPATH += .

# Input
HEADERS += ../../Plugin.hpp ../../dubway-global.hpp
SOURCES += test.cpp
